### ISSUE TITLE
local variable 'con_methods' referenced before assignment

### ISSUE THREAD

**Issue by pasadesh** [mne-tools/mne-connectivity#114] opened 2022-11-24 13:18 UTC
#### Describe the bug
`local variable 'con_methods' referenced before assignment (line 1120 in the spectral_connectivity_epochs function).`

#### Steps to reproduce
Here I run the following code:
```
con_methods = ['pli', 'wpli2_debiased', 'ciplv']
con = spectral_connectivity_epochs(label_ts, method=con_methods, mode='multitaper', sfreq=sfreq, fmin=fmin, fmax=fmax,
                                    faverage=True, mt_adaptive=True, n_jobs=1)
```
as it is in the example (https://mne.tools/mne-connectivity/dev/auto_examples/mne_inverse_label_connectivity.html)
and I get the following error...
`local variable 'con_methods' referenced before assignment (line 1120 in the spectral_connectivity_epochs function)`.

**Comment by ruuskas** [comment] 2022-11-24 13:39
Have you tried [downloading](https://mne.tools/mne-connectivity/dev/_downloads/362653bdca0374b7bfa9d129d67db66f/mne_inverse_label_connectivity.py) the example and running it with the latest version? 

I tried and wasn't able to reproduce the problem.

**Comment by ruuskas** [comment] 2022-11-24 15:03
What do you mean by running only that one line of code? 
All code in the script should be run to assign values for the arguments to `spectral_connectivity_epochs`.

**Comment by adam2392** [comment] 2022-11-24 15:27
What is the output for mne.sys_info?

**Comment by pasadesh** [comment] 2022-11-24 15:30
`function mne.utils.config.sys_info(fid=None, show_paths=False, *, dependencies='user')`

**Comment by adam2392** [comment] 2022-11-24 15:37
What is the output of running it?

https://mne.tools/dev/generated/mne.sys_info.html

**Comment by pasadesh** [comment] 2022-11-24 15:38
Platform:         Windows-10-10.0.19044-SP0
Python:           3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Executable:       e:\ZNZ\eeg_resting-state\.venv\python.exe
CPU:              Intel64 Family 6 Model 60 Stepping 3, GenuineIntel: 8 cores
Memory:           7.9 GB

**Comment by pasadesh** [comment] 2022-11-24 15:41
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?c04a536e-abae-49ee-a7b0-dbc753a2f396)
Platform:         Windows-10-10.0.19044-SP0
Python:           3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Executable:       e:\ZNZ\eeg_resting-state\.venv\python.exe
CPU:              Intel64 Family 6 Model 60 Stepping 3, GenuineIntel: 8 cores
Memory:           7.9 GB

mne:              1.2.1
numpy:            1.21.6 {OpenBLAS 0.3.17 with 8 threads}
scipy:            1.9.1
matplotlib:       3.6.2 {backend=module://matplotlib_inline.backend_inline}

sklearn:          1.1.2
numba:            0.55.0
nibabel:          4.0.2
nilearn:          0.9.2
dipy:             1.5.0
openmeeg:         Not found
cupy:             Not found
pandas:           1.4.4
pyvista:          0.36.1 {OpenGL 4.3.0 - Build 20.19.15.4835 via Intel(R) HD Graphics 4600}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.3
vtk:              9.2.2
qtpy:             2.2.0 {PyQt5=5.15.2}
ipympl:           Not found
...
mne_features:     Not found
mne_qt_browser:   0.4.0
mne_connectivity: 0.5.0.dev0
mne_icalabel:     Not found

**Comment by ruuskas** [comment] 2022-11-25 09:18
Hi @pasadesh!

The problem is that `label_ts` is a generator, which gets exhausted when `spectral_connectivity_epochs` is called for the first time. 

If you want to run `spectral_connectivity_epochs` multiple times, you should replace this:
```python
label_ts = mne.extract_label_time_course(
    stcs, labels, src, mode='mean_flip', return_generator=True)
```
with this:
```python
label_ts = mne.extract_label_time_course(
    stcs, labels, src, mode='mean_flip', return_generator=False)
```

This is not a bug in the code but rather a Python feature.

**Comment by adam2392** [comment] 2022-11-28 16:04
Closing as this is not a bug. Feel free to re-open if you disagree @pasadesh

**Closed by adam2392** 2022-11-28 16:04 UTC
